
<nav><ul>
   <li class='home'><a title="go home" href="./">home</a></li>
   <li class='rot'><a title="menu rotation" href="javascript:toggleNav();"></a></li>
   <li><a href='javascript:void(0);' class='btn'>docs</a>
      <ul class='sub'>
         <li><a class='btn' href="README.md" title="SEO, content management, and blogging using conventional files.">README</a></li>
      </ul></li>
   <li><a href='javascript:void(0);' class='btn'>help</a>
      <ul class='sub'>
         <li><a class='btn' href="index.php" title="management, and blogging using conventional files. Drop files onto the server and FirstPage takes care of the rest!">About FirstPage</a></li>
      </ul></li>
</ul></nav>

